server:
  port: 8761

spring:
    application:
        name: msvc-server
    ## Esta configuracion es temporal, ya que se debe configurar un config server 
    ## para que el microservicio pueda obtener la configuracion de manera centralizada
    config:
        import: optional:configserver:http://localhost:8888

eureka:
    instance:
        hostname: localhost
    
    client:
        ## esta configuracion se registra asi mismo por defecto, pero como es "false" no se registra en el eureka server
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:${server.port}/eureka/

