server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost

  client:
    ## esta configuracion se registra asi mismo por defecto, pero como es "false" no se registra en el eureka server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

