## Se borra todo lo demas y dejamos solo eso ya que en el "Config Server" ya tenemos toda la configuracion
## de la base de datos y demas, solo necesitamos que el microservicio student se conecte al config server
## para obtener la configuracion de manera centralizada
spring:
  application:
    name: msvc-gateway
  config:
    import: "optional:configserver:http://localhost:8888"

